### ISSUE TITLE
Can't insert phone number on the login page

### ISSUE THREAD

**Issue by JakoDel** [arma7x/telekram#2]
There are buttons configured to open the country list and to write the prefix by yourself, but... no insert phone number button.
Also,  there is no cursor soo yeah I can't figure out how to select the number box (pressing the up/down buttons doesn't do anything)

**Comment by arma7x** [comment]
LSK    -> Change Prefix
Enter  -> Select country
Call    -> Enter Phone number
RSK   -> Next

RSK/Enter -> Dialog(YES)
BackKey    -> Dialog(NO)

**Comment by JakoDel** [comment]
welp
thanks a lot :)

**Comment by dinzysl** [comment]
i can not login in telegram like i have entered the right code there's no proceed button :0
im stuck at "Enter your code" page 
even tho i entered my code ion know what to do there aint proceed button i entered the correct codei litterally pressed every button even rsk and d-pad center

**Comment by arma7x** [comment]
I can't reproduce the bug. Just tested and I can re-login into my Telegram account on KaiOS

**Comment by zoelilylain** [comment]
also experiencing the inability to submit the code to login. Cingular Flex 2.5.4

**Comment by arma7x** [comment]
> also experiencing the inability to submit the code to login. Cingular Flex 2.5.4

You received login code but **unable to enter the code** or **nothing happen after you entered the code** ?

**Comment by zoelilylain** [comment]
Nothing happens after entering the code. Center key does nothing, nor does rsk

**Comment by arma7x** [comment]
> Nothing happens after entering the code. Center key does nothing, nor does rsk

After you enter the code, the app will auto submit. I can reproduce the bug and my device can re-login into my Telegram account

**Comment by zoelilylain** [comment]
> > Nothing happens after entering the code. Center key does nothing, nor does rsk
> 
> After you enter the code, the app will auto submit. I can reproduce the bug and my device can re-login into my Telegram account

ive done this 5 times and it hasent auto submitted even once but ill try again

**Comment by arma7x** [comment]
Try login web client https://web.telegram.org/?legacy=1#/login

**Comment by zoelilylain** [comment]
it just gets stuck. it wont continue past the code. I hit next, it "checks code" for two seconds and then does nothing

**Comment by zoelilylain** [comment]
hold on i might be getting rate-limited or something

**Comment by arma7x** [comment]
Or maybe you can try login by using latest client(WIP) https://github.com/arma7x/svelte-telekram

**Comment by zoelilylain** [comment]
fails to build on my machine:
`[!] Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts
Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts
    at error (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22287:24)
    at Array.from (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22250:26)`

**Comment by arma7x** [comment]
> fails to build on my machine: `[!] Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts at error (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:198:30) at ModuleLoader.handleResolveId (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22287:24) at Array.from (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22250:26)`

https://github.com/arma7x/svelte-telekram/issues/2

**Comment by zoelilylain** [comment]
> > fails to build on my machine: `[!] Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts Error: Could not resolve '../telegram_key' from src/utils/bootstrap.ts at error (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:198:30) at ModuleLoader.handleResolveId (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22287:24) at Array.from (/home/lynciac/Desktop/svelte-telekram/node_modules/rollup/dist/shared/rollup.js:22250:26)`
> 
> [arma7x/svelte-telekram#2](https://github.com/arma7x/svelte-telekram/issues/2)

should prolly put that in the readme
