### ISSUE TITLE
Trouble with playing music on Nokia 8000, during using TeleKram

### ISSUE THREAD

**Issue by nallion** [arma7x/telekram#6]
Hello, I buy Nokia 8000 device. Install Telekram and found issue.

When i listen music (FM Radio / Mp3 player / Stream etc) & run simulateosly telekram, music stopped when TeleKram loading contactlist. Music triangle has not appear on top of screen, Telekram capture main audio channel. Can you help me fix issue, I cannot find way...

**Comment by arma7x** [comment]
The issue is music stopped when TeleKram loading contactlist or when Telekram capture main audio channel ?

**Comment by nallion** [comment]
all backgroud audio stops when loading application telekram
i make small vid to demonstrate problem

https://youtu.be/qUzldn-5llE

**Comment by arma7x** [comment]
I can't reproduce this bug on my Nokia 8110 4G. 

**Test**: Play song via stock music app(also via K-Music) then open Telekram while the music still playing
**Result**: Telekram not crash & music app still playing the song

**Comment by nallion** [comment]
Yep, this trouble only with nokia 8000. All music apps (stock music app, k-music) crashed when TeleKram loaded, music stop plays. Crash are visible with webide too. I cannot found some firmware alternatives, and i cannot found fix for this issue. Firmware on my Nokia lastest.

**Comment by arma7x** [comment]
Maybe you should open Telekram first then minimize it. After that, play the music, minimize it and finally re-open TeleKram again

**Comment by nallion** [comment]
this is patrially helpful, because Telekram sometimes fully closes (kills) after minimizing...

**Comment by arma7x** [comment]
Maybe due to low RAM/device memory

**Comment by nallion** [comment]
Thank you, Due to my research phone have kaios 2.5.4 and very low free ram(((

**Comment by nallion** [comment]
I found solution!!!
I root my Nokia 8000 and disable mechanism "low memory killer" , by adding this string to boot script

echo "0" > /sys/module/lowmemorykiller/parameters/enable_lmk

After this, KaiOS stops killing applications and support enhanced multitasking. Thanks for idea.
