### ISSUE TITLE
Updated source using Telegram Z

### ISSUE THREAD

**Issue by thetechgeekster** [arma7x/telekram#7]
Hi! I am using your app and it is amazing. I'm happy that I can use Telegram on my KaiOS Device. Some of my contacts though appear as "Unsupported User" and Telegram promts me to update my outdated app. Could your adaptation of Telegram Web be based on the newer Telegram Web Z source (https://github.com/Ajaxy/telegram-tt)?

**Comment by arma7x** [comment]
kaios 2.5 not support WASM
